### ISSUE TITLE
"build/envsetup.sh" missing in TinyVision-tina.0.0.2

### ISSUE THREAD

**Issue by developcf** [YuzukiHD/TinyVision#28]
When I unzip the TinyVision-tina.0.0.2.zip and combine its patch package(tina-bsp-tinyvision.tar.gz). I can't find build/envsetup.sh under the top path.

**Comment by YuzukiTsuru** [comment]
TinyVision-tina.0.0.2.zip only a patch for tinyvision, you need to get full tina5.0 and apply this patch

```
$ repo init -u https://sdk.aw-ol.com/git_repo/V853Tina_Open/manifest.git -b master -m tina-v853-open.xml
$ repo sync
```

You need https://bbs.aw-ol.com/ account to download it, make sure your fourm level is LV2
