### ISSUE TITLE
Camera gc2053 is not initialized

### ISSUE THREAD

**Issue by tuuzdu** [YuzukiHD/TinyVision#29]
Camera works good on Lizard board, but not starting on TinyVision. Tried 0.0.1 and 0.0.2 versions, same log.
```

Load mpp modules
insmod: can't insert '/lib/modules/4.9.191/videobuf2-core.ko': No such file or directory
insmod: can't insert '/lib/modules/4.9.191/videobuf2-memops.ko': No such file or directory
insmod: can't insert '/lib/modules/4.9.191/videobuf2-v4l2.ko': N[    4.839192] [VIN_WARN]sensor_helper_probe: cannot get sensor0_cameravdd supply, setting it to NULL!
o such file or directory
[    4.850007] [VIN_WARN]sensor_helper_probe: cannot get sensor0_iovdd supply, setting it to NULL!
[    4.861958] [VIN_WARN]sensor_helper_probe: cannot get sensor0_avdd supply, setting it to NULL!
[    4.871667] [VIN_WARN]sensor_helper_probe: cannot get sensor0_dvdd supply, setting it to NULL!
[    4.985950] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    4.995466] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.005030] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.014402] [VIN_DEV_I2C]gc2053_mipi sensor read retry = 2
[    5.235879] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.245389] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.254921] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.264283] [VIN_DEV_I2C]gc2053_mipi sensor read retry = 2
[    5.485874] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.495382] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.504909] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.514268] [VIN_DEV_I2C]gc2053_mipi sensor read retry = 2
[    5.735893] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.745403] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.754926] sunxi_i2c_do_xfer()1974 - [i2c3] incomplete xfer (status: 0x20, dev addr: 0x37)
[    5.764495] [VIN_DEV_I2C]gc2053_mipi sensor read retry = 2
[    5.770709] [gc2053_mipi] error, chip found is not an target chip.
[    5.790119] [VIN_ERR]registering gc2053_mipi, No such device!
insmod: can't insert '/lib/modules/4.9.191/sunxi_aio.ko': No such file or directory
insmod: can't insert '/lib/modules/4.9.191/sunxi_eise.ko': No such file or directory

```

**Comment by YuzukiTsuru** [comment]
Lizard board camera cannot use in tinyvision

**Comment by tuuzdu** [comment]
> Lizard board camera cannot use in tinyvision  

I thought that is gc2053. What is model of lizard board camera?  

I ordered gc2053 from Aliexpress, but it's not also 2053 I suppose 
![image](https://github.com/YuzukiHD/TinyVision/assets/5239268/96f17e22-3c28-4ea8-9429-a43091192de7)

**Comment by YuzukiTsuru** [comment]
Please make sure pinout is same as tinyvision

**Comment by tuuzdu** [comment]
I think pinout is not same, if information is right :( What is exact model of camera that you use for TinyVision? Do you have datasheet?   
![image](https://github.com/YuzukiHD/TinyVision/assets/5239268/0dfedb91-293f-40dc-968b-501a6bbfd6ba)
![image](https://github.com/YuzukiHD/TinyVision/assets/5239268/d8fb36f4-777c-4794-bc07-445b04853f24)

**Comment by tuuzdu** [comment]
Or is this possible to fix pinout in driver?

**Comment by YuzukiTsuru** [comment]
no, you need to use adapt board for it

**Comment by tuuzdu** [comment]
Could you attach datasheet of camera that you used?

**Comment by YuzukiTsuru** [comment]
![image](https://github.com/YuzukiHD/TinyVision/assets/12003087/8db53a95-13dd-448f-b619-1bcde5fa5458)

**Comment by tuuzdu** [comment]
> ![image](https://private-user-images.githubusercontent.com/12003087/330450174-8db53a95-13dd-448f-b619-1bcde5fa5458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDE0OTIsIm5iZiI6MTcxNzI0MTE5MiwicGF0aCI6Ii8xMjAwMzA4Ny8zMzA0NTAxNzQtOGRiNTNhOTUtMTNkZC00NDhmLWI2MTktMWJjZGU1ZmE1NDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDExMjYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YTY1ZGY0N2VkZWVjNmQ1NGQzYWQ2MjY2NDQyNTZiMzEzZWZlN2ZjZGFmZjMzM2IwN2VhYjk0ZDU4YjVhZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3JvQqfryXdc_5wkYi3Ym0ax9wimAve2rK3wBlMgEIaw)

I bought this camera from Taobao. Everything is working
