### ISSUE TITLE
Is the LED next to USB connector LED3? Is it for power indication? 

### ISSUE THREAD

**Issue by DeqingSun** [YuzukiHD/TinyVision#34]
Hi, there is a color-changing LED next to the USB connector. It seems to be a 2-pin LED, and it seems to match the LED3 between 3.3V and GND.

Is the purpose of the LED just for showing there is power? Is the color changing feature used for indicate undervoltage? Like blue goes away?

**Comment by YuzukiTsuru** [comment]
Yes, you can find this type of Colored LED in any YuzukiHD provided hardware
