### ISSUE TITLE
Enable USB as host

### ISSUE THREAD

**Issue by dumtux** [YuzukiHD/TinyVision#36]
How to enable USB as host?
I'd like to use USB webcam as camera input, for makeing a webcam + TinyVision as a customizable intelligent IP camera.

**Comment by YuzukiTsuru** [comment]
cat /sys/devices/platform/soc/usbc0/usb_host

**Comment by dumtux** [comment]
![image](https://github.com/user-attachments/assets/2df5e441-89fe-4c1b-9355-cd38aa08584f)

Thank you!
My board is using V851S, and I added an USB hub on board, currently connected a webcam to it.
It seems like working!

I'm using your docker image for build env setup.

I tried to add `usbutils` in `make manuconfig`, but it said due to confliction with `lsudev-zero`, compilation failed.
I also experienced similar confliction issue when I tried to install `mjpg-streamer`.

`fswebcam` was okay for build.
But after that, I could not find `fswebcam` from the command line.

Can you advise?

**Comment by dumtux** [comment]
And as the USB host is working, I expected to see `/dev/videoinput0` or something similar device to be used as input of `fswebcam` or `mjpg-streamer`.
How can I make this working?

**Comment by dumtux** [comment]
I plugged an USB webcam and a SIM7600 USB dongle.
After running `cat /sys/devices/platform/soc/usbc0/usb_host`
I could get this,
![image](https://github.com/user-attachments/assets/e12123e0-b1ca-481b-8daf-43ea3e234629)

**Comment by dumtux** [comment]
I was expecting to see something like this:
```$ ls -l /sys/bus/usb/devices/*/driver | grep video
lrwxrwxrwx 1 root root 0 Oct  1 01:20 /sys/bus/usb/devices/1-8:1.0/driver -> ../../../../../../bus/usb/drivers/uvcvideo
lrwxrwxrwx 1 root root 0 Oct  1 01:20 /sys/bus/usb/devices/1-8:1.1/driver -> ../../../../../../bus/usb/drivers/uvcvideo
$
```

In the OS buildroot, I ran `make menuconfig` and searched `uvcvideo`, but the package didn't seem like included.

**Comment by dumtux** [comment]
The further USB camera questions are moved to [Issue #37 ](https://github.com/YuzukiHD/TinyVision/issues/37)
